# 
# File: user-auth-backend/server/docker-compose.yml ...
# 
services:
  # User Authentication Backend Service ...
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ./server/.env

    image: auth-backend/backend:latest




# Note: this docker-compose file works as i am using mongoDB Atlas for the database.
#       If you want to use a local MongoDB instance, you can add a mongo service
#       and link it to the backend service.
#       Make sure to update the connection string in the .env file accordingly.