# services:
#   user-auth-frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: mern-auth-frontend
#     environment:
#       API_URL: http://localhost:5000/api
#     hostname: user-auth-frontend
#     image: user-auth/web:latest
#     networks:
#       - user_auth_app_network
#     ports:
#       - mode: ingress
#         target: 3000
#         published: 8080
#         protocol: tcp
#     restart: unless-stopped
# networks:
#   user_auth_app_network:
#     name: user_auth_app_network
#     # external: true