# 
# File: user-auth-frontend/docker-compose.yml
# 
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000
    container_name: auth-frontend
    ports:
      - "3000:80"
    image: auth-frontend/frontend:latest
